name: Publish Node.js Package

on:
  push:
    tags:
      - '*'

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          scope: '@weni'
      - name: Install Dependencies
        run: yarn
      - name: Run Lint
        run: yarn lint --fix --quiet
      - name: Build Bundle
        run: yarn build-bundle
      - name: Publish Package
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
